rest:
  auth-open: true #jwt鉴权机制是否开启(true或者false)
  sign-open: true #签名机制是否开启(true或false)
  message-path: http://webt.lilang.com/base-msgservice/Create  # 消息接口地址
  message2-path: http://webt.lilang.com:9001/tl_zmd/MSGSendBase.ashx?msgtype=gd&sysid=0&userssid=1&userid=0&username=LilanzEShopReg&phone={0}&msg={1}  #短信接口地址
  news-path: http://webt.lilang.com:9001/tl_zmd/MSGSendBase.ashx?msgtype=gd&sysid=0&userssid=1&userid=0&username=LilanzEShopReg&phone={0}&msg={1}  #短信接口地址

jwt:
  header: Authorization   #http请求头所需要的字段
  secret: mySecret        #jwt秘钥
  expiration: 604800      #7天 单位:秒
  auth-path: auth         #认证请求的路径
  md5-key: randomKey      #md5加密混淆key

server:
  port: 8014 #项目端口

mybatis-plus:
  mapper-locations: classpath*:com/stylefeng/guns/rest/**/mapping/*.xml,classpath*:com/md/**/mapping/*.xml
  typeAliasesPackage: com.stylefeng.guns.rest.common.persistence.model
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用

spring:
  datasource:
      url: jdbc:mysql://120.78.213.77:3306/testshop?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: root
      password: md123456.
      filters: log4j,wall,mergeStat

logging:
  level.root: info
  level.com.stylefeng: debug
  path: logs/
  file: guns-rest.log